### ISSUE TITLE
How to Measure Success?

### ISSUE THREAD

**Issue by rooftopsparrow** [BK4LYFE/SpicyChi-King#10]
## How do we measure success?

- We must document the "important things" we want to be measuring and how to measure them

**Comment by brownbread269** [comment]
Probably the first aspects we can use is number of contributions or number of hours worked on something. And we post on our Github what we did and how long it took and the difficulty factor.

**Comment by Jadencua** [comment]
I don't think this is necessarily a good system of measurement. This favors low quality, speedy contributions.

**Comment by rooftopsparrow** [comment]
I think it should be more opaque:

1. Measure number of goals met

**Comment by Jadencua** [comment]
I agree. Setting small goals and meeting them is a good way to measure success and progress.

**Comment by rooftopsparrow** [comment]
2. Measure the amount of progress towards a milestone.

**Comment by Jadencua** [comment]
> 1. Measure number of goals met
> 2. Measure the amount of progress towards a milestone.

So, we agree that this is the method/metric we will use to measure success and progress?
