### ISSUE TITLE
Find an introductory ticket write contribution

### ISSUE THREAD

**Issue by rooftopsparrow** [BK4LYFE/SpicyChi-King#20]
MRS filters available tickets to work on at badge level 1 to introductory tickets.

Find a ticket to contribute to and document it.

**Comment by Jadencua** [comment]
The group decided and chose to work on the ticket "ConceptResource to GET concepts of a given class", labeled as RESTW-817 and located [here](https://issues.openmrs.org/browse/RESTWS-817?jql=project%20%3D%20RESTWS%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(jnich)%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC)
