### ISSUE TITLE
How to Communicate

### ISSUE THREAD

**Issue by Jadencua** [BK4LYFE/SpicyChi-King#7]
How does the community want to communicate with one another?

**Comment by Radams5000** [comment]
We can use Discord because that's what the kids use. Microsoft teams would work because we all have it. I think Dr. Paul set us up as group on Canvas.

**Comment by rooftopsparrow** [comment]
I think we should have multiple ways we communicate.

- For adhoc communication, there should be a chat style channel for general day to day discussions.
- There should be a focused discussion forum for focused questions/topics
- For long term communication, we should have a wiki or website for reference material to communicate with the community.
- We could also consider newsletter, twitter, RSS feed, blog for announcement style communications.

**Comment by Jadencua** [comment]
Ryan,
That's correct, we have been made a group on Canvas.

I am in favor of having a Discord channel because it's free and easy to use for chat style discussion and calls.
We could use this "Issues" page for more focused questions and topics. The wiki could be used for documentation of efforts.

**Comment by brownbread269** [comment]
I also vote for Discord. I was wondering if there was a place us all to have an online hangout presence, so maybe a channel in discord then?

**Comment by rooftopsparrow** [comment]
Sounds like like majority for Discord! Lets make an issue to create a discord channel.

**Comment by Jadencua** [comment]
@Radams5000

**Comment by brownbread269** [comment]
@Radams5000 mentioned a second time as a test of github's features.

**Comment by Jadencua** [comment]
Here is the Discord channel that I made. Please join. https://discord.gg/U76CRUZR

**Comment by Radams5000** [comment]
@Jadencua It works. Go with

**Comment by Jadencua** [comment]
Glad we could come to a consensus. We will use Discord for communications and this wiki for documentation. The wiki will be updated to reflect this issue.
