### ISSUE TITLE
How does the community make decisions?

### ISSUE THREAD

**Issue by rooftopsparrow** [BK4LYFE/SpicyChi-King#8]
There needs to be a defined process for how the community makes decisions and how that decision is broadcast to the community.

**Comment by rooftopsparrow** [comment]
I propose that we limit decision making to the core maintainers of the project community through simply majority, and/or benevolent dictatorship. 

Decisions made should be documentation entries for community reference.

**Comment by Jadencua** [comment]
I second your proposal.

@Radams5000 @dgiri12 What say you?

**Comment by brownbread269** [comment]
@Radams5000 what say you? I say yes

**Comment by Radams5000** [comment]
@rooftopsparrow @Jadencua @dgiri12 
I agree with going with the simple majority. Since the 3 of you already made the decision, my vote doesn't really matter.

**Comment by Jadencua** [comment]
By overwhelming majority, voting has passed. Issue closed.
