### ISSUE TITLE
Create Discord Issue and Document For Community

### ISSUE THREAD

**Issue by rooftopsparrow** [BK4LYFE/SpicyChi-King#9]
Create a community Discord Server and document how to join the server.

**Comment by Jadencua** [comment]
Discord server created!

**Comment by rooftopsparrow** [comment]
How do users join the discord? Please document somewhere, I would suggest a wiki page.

**Comment by Jadencua** [comment]
Here is a link that *should* never expire. Thank you for your decisive leadership.

https://discord.gg/6Bm4yNXKrH
